### PR TITLE
Remove click hook

### PR DESCRIPTION
**Pull request by mariogrip**
To make content-hub usable on system that do not use click, lets drop the click hook and use QFileWatcher to watch for file changes to the peer json files instead of relying of click hook to update our registry. 

Before:
Install click with content-hub.json file -> click hook runs and updates registry

Now:
Install click with content-hub.json file -> QFileWatcher see there is a change and  updates registry

The end result the exact same. 

This pulls in changes from bionic where canonical already tough about this :)

### CODE REVIEW

**Comment by mardy** [comment]
I'm not really a fan of this change, I would have left the click hook as a separate executable, and just have the QFileSystemWatcher invoke the hook when a change is detected.

But I cannot work on this right now, so if you don't have the time to rework this, then I'm fine with these changes.

**Comment by mariogrip** [comment]
> I'm not really a fan of this change, I would have left the click hook as a separate executable, and just have the QFileSystemWatcher invoke the hook when a change is detected.
> 
> But I cannot work on this right now, so if you don't have the time to rework this, then I'm fine with these changes.

If i read you correctly, you want to have the QFileWatcher on a seperate executable? May i ask why?

**Comment by mardy** [comment]
> > I'm not really a fan of this change, I would have left the click hook as a separate executable, and just have the QFileSystemWatcher invoke the hook when a change is detected.
> > But I cannot work on this right now, so if you don't have the time to rework this, then I'm fine with these changes.
> 
> If i read you correctly, you want to have the QFileWatcher on a seperate executable? May i ask why?

Sorry for the late reply :-)

Not really, the QFileWatcher needs to be in the contenthub itself, but once a change is detected it could just execute the existing external click hook.

The reasons are:
1. A separate tool makes it much more easier to test that the tool is behaving properly (and also that the manifests are written properly)
2. Memory isolation: once the script is executed, it dies. All of its memory is freed, including any leaks. :-)
3. A separate tool might be reusable by distributions (and who knows, maybe we won't need the QFileWatcher even): for example, as a dpkg trigger (when an app supporting the content-hub is installed), or as a snap connector.

But for me the first point is the most important.

**Comment by UniversalSuperBox** [comment]
content-hub has moved to https://gitlab.com/ubports/core/content-hub. If this PR is still relevant, please recreate it there.

**Pull request closed without merging**
