### PR TITLE
Use qmlplugindump-qt5

### LINKED ISSUE #4: Unknown option 'qt'
I get this error when building on Arch GNU/Linux (amd64)
```
Unknown option 'qt'.
make[2]: *** [docs/qml/CMakeFiles/qmldoc.dir/build.make:58: docs/qml/CMakeFiles/qmldoc] Error 1
make[1]: *** [CMakeFiles/Makefile2:4153: docs/qml/CMakeFiles/qmldoc.dir/all] Error 2
```

```
Invalid argument: -qt=qt5
make[2]: *** [import/Ubuntu/Content/CMakeFiles/Content_generated_files.dir/build.make:58: import/Ubuntu/Content/plugins.qmltypes] Error 1
```

The troubling options resides in `doc/qml/CMakeLists.txt` on line 6, and in (`import/Ubuntu/Content/CMakeLists.txt`).

The issue is related to `qdoc`: `/usr/bin/qdoc -qt=qt5`

Same as https://github.com/ubports/ubuntu-download-manager/issues/6

### PR DESCRIPTION
**Pull request by z3ntu**
Fixes #4

### CODE REVIEW

**Comment by z3ntu** [comment]
No idea how to solve this cross-distro as `qmlplugindump-qt5` isn't available on Ubuntu (and maybe other distros).

**Review by UniversalSuperBox — CHANGES_REQUESTED** [review]
The thing is, Debian-based OSs use QtChooser to switch between qt4 and qt5 (since many of the tools have the same names). A packaging difference on another OS is insufficient reason to make this change in a breaking way. Instead, can you find a way to detect if we have one binary, and if not, use the other?

**Comment by z3ntu** [comment]
Something detecting that should be integrated in cmake-extras then I guess. I'll see if I can find some time to do that.

**Comment by dobey** [comment]
I think the correct solution for this issue would be to just drop the `-qt=qt5` argument, and use `QT_SELECT=qt5` when building. Going to close this for now as it's over a year since any activity, and more focus has moved to updated xenial branches with newer Qt support.

**Pull request closed without merging**
